// constants/seoKeywords.ts
export const SEO_KEYWORDS = [
    "best ad agency in Pune Maharashtra",
    "top advertising agency Pune",
    "leading ad agency in Pune",
    "Pune creative agency",
    "digital marketing agency Pune",
    "outdoor advertising Pune",
    "billboard advertising Pune",
    "EV advertisement Pune",
    "cycle advertisement Pune",
    "social media agency Pune",
    "branding agency Pune",
    "Pune hoarding agency",
    "advertising company in Pune",
    "Pune marketing agency",
    "best ad agency Maharashtra",
    "Pune media buying agency",
    "Pune campaign management",
    "Pune ad agency for startups",
    "Pune ad agency for corporates",
    "Pune advertising experts",
    "Pune ad agency reviews",
    "award-winning ad agency Pune",
    "Pune ad agency for billboards",
    "Pune ad agency for EV ads",
    "Pune ad agency for cycle ads",
    "Pune ad agency for social media",
    "Pune ad agency for branding",
    "Pune ad agency for hoardings",
    "Pune ad agency for digital ads",
    "Pune ad agency for print ads",
    "Pune ad agency for lead generation",
    "Pune ad agency for website design",
    "Pune ad agency for content creation",
    "Pune ad agency for flyer design",
    "Pune ad agency for video ads",
    "Pune ad agency for influencer marketing",
    "Pune ad agency for campaign analytics",
    "Pune ad agency for ROI",
    "Pune ad agency for startups",
    "Pune ad agency for SMEs",
    "Pune ad agency for large brands",
    "Pune ad agency for local businesses",
    "Pune ad agency for national brands",
    "Pune ad agency for hoarding analytics",
    "Pune ad agency for CPM",
    "Pune ad agency for demographic targeting",
    "Pune ad agency for location-based ads",
    "Pune ad agency for 360 view",
    "Pune ad agency for Google street view",
    "Pune ad agency for real-time tracking",
    "Pune ad agency for campaign planning",
    "Pune ad agency for design support",
    "Pune ad agency for printing support",
    "Pune ad agency for route mapping",
    "Pune ad agency for approvals",
    "Pune ad agency for deployment",
    "Pune ad agency for execution",
    "Pune ad agency for analytics",
    "Pune ad agency for visibility metrics",
    "Pune ad agency for illuminated hoardings",
    "Pune ad agency for day night visibility",
    "Pune ad agency for size elevation",
    "Pune ad agency for distance visibility",
    "Pune ad agency for static hoardings",
    "Pune ad agency for digital hoardings",
    "Pune ad agency for rotating hoardings",
    "Pune ad agency for city-wise ads",
    "Pune ad agency for area-wise ads",
    "Pune ad agency for customizable routes",
    "Pune ad agency for daily running",
    "Pune ad agency for prime locations",
    "Pune ad agency for 3D elements",
    "Pune ad agency for eco-friendly ads",
    "Pune ad agency for hyperlocal targeting",
    "Pune ad agency for scalable solutions",
    "Pune ad agency for small brands",
    "Pune ad agency for large campaigns",
    "Pune ad agency for client testimonials",
    "Pune ad agency for renowned clients",
    "Pune ad agency for budget optimization",
    "Pune ad agency for high ROI",
    "Pune ad agency for lead generation",
    "Pune ad agency for collaborations",
    "Pune ad agency for website building",
    "Pune ad agency for website management",
    "Pune ad agency for FAQ",
    "Pune ad agency for contact us",
    "Pune ad agency for campaign audit",
    "Pune ad agency for free consultation",
    "Pune ad agency for creative solutions",
    "Pune ad agency for marketing solutions",
    "Pune ad agency for data-driven ads",
    "Pune ad agency for transparent analytics",
    "Pune ad agency for client support",
    "Pune ad agency for award-winning campaigns",
    "Pune ad agency for innovative ads",
    "Pune ad agency for brand visibility",
    "Pune ad agency for business growth",
    "Pune ad agency for advertising success",
    "Pune ad agency for expert team",
    "Pune ad agency for trusted partners",
  ];
  
  // To use as a comma-separated string in your <meta> tag:
  export const SEO_KEYWORDS_STRING = SEO_KEYWORDS.join(", ");
  